server:
  port: 3344
spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: http://10.6.208.86:8081/013945/cloud2021.git
          default-label: master
          skipSslValidation: true
          search-paths:
            - springcloud-config
          force-pull: true
          timeout: 10
  #          proxy:
  #            host: 127.0.0.1
  #            port: 7890
  #            scheme: http
  #rabbitmq相关配置
  rabbitmq:
    host: 10.6.208.146
    port: 5672
    username: admin
    password: admin
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,,http://eureka7003.com:7003/eureka  # 集群版
  instance:
    prefer-ip-address: true
    instance-id: config3344
##rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: busrefresh