server:
  port: 3344
spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chill-lee/cloud2021.git
          search-paths:
            - springcloud-config
          default-label: master
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,,http://eureka7003.com:7003/eureka  # 集群版
  instance:
    prefer-ip-address: true
    instance-id: config3344